defaults:
  - _self_ 
  - net: default 

seed: 42


net:
  num_classes: 6
  beta: 0.030589952331743383
  #lstm_weigts: [1.5, 1.5, 1.5, 0.6, 0.6, 1.5]

trainer:
  max_epochs: 95
  log_every_n_steps: 10
  

callbacks:
  patience_AE: 20
  patience_LSTM: 39

dataset:
  data_dir: "${oc.env:PWD}/data"
  batch_size: 32
  val_split: 0.3

wandb :
  project: "FDS_PROJECT"
  entity: "catairu-sapienza-universit-di-roma"
  name: "BNsoloencoder_provaCA"