defaults:
  - _self_ 
  - net: default 

seed: 42


net:
  num_classes: 6
  beta: 0.17818
  lstm_weigts: [0.95,1.06,1.19,1.13,0.84,0.91]

trainer:
  max_epochs: 119
  log_every_n_steps: 10
  

callbacks:
  patience_AE: 21
  patience_LSTM: 20

dataset:
  data_dir: "${oc.env:PWD}/data"
  batch_size: 192
  val_split: 0.16768725958216624

wandb :
  project: "FDS_PROJECT"
  entity: "catairu-sapienza-universit-di-roma"
  name: "paperf_provaCA"