defaults:
  - _self_ 
  - net: default 

seed: 42


net:
  num_classes: 6
  beta: 0.05

trainer:
  max_epochs: 100
  log_every_n_steps: 10
  patience: 7

dataset:
  data_dir: "${oc.env:PWD}/data"
  batch_size: 128
  val_split: 0.3

wandb :
  project: "FDS_PROJECT"
  entity: "catairu-sapienza-universit-di-roma"
  name: "paperf_provaCA"