_target_: net.cnn.DecoderWrapper
#in_channels:        
##out_channels: 9       
#kernel_size: 3
#stride: 2
##padding: 1
#output_padding: 1
#use_batchnorm: true

in_channels: 256  # (Or 256 if you used the evolving structure)

# 2. Architecture: This defines the layers. 
# It MUST end with 9 (your original sensors)
layer_widths: [128, 64, 9] 
kernel_size: 5
stride: 2
output_padding: 1
use_batchnorm: true