_target_: net.cnn.EncoderWrapper
#in_channels: 9
##out_channels: ${net.width}
#layer_widths: [64, 64, 64]
#kernel_size: 3
#pool_size: 1

in_channels: 9
layer_widths: [64, 128, 256]
kernel_size: 5

# --- ADD THIS ---
stride: 2