
_target_: net.mlp.ConfigurableMLP  # <--- Update path
hidden_size: [128, 64] # Corresponds to ConfigurableMLP argument
output_size: 6          # Corresponds to ConfigurableMLP argument
dropout: 0.3            # Can be list [0.3, 0.3] or float 0.3
activation_type: "ELU"  # Corresponds to ConfigurableMLP argument